"""Add RBAC, Module system, Audit log, AD integration models

Revision ID: 1b9654c0c3d3
Revises: 001_initial
Create Date: 2026-08-27 19:47:45.869612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9654c0c3d3'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_index(op.f('ix_users_ad_dn'))
        batch_op.create_unique_constraint('uq_users_ad_dn', ['ad_dn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('uq_users_ad_dn', type_='unique')
        batch_op.create_index(op.f('ix_users_ad_dn'), ['ad_dn'], unique=True)
    # ### end Alembic commands ###