from app.db.session import Base
from app.models.ad_integration import ADConfig, ADGroupMapping, ADSyncLog, ADSyncStatus
from app.models.audit import AuditLog
from app.models.buildings import Building, Room, RoomType, Site, UsageType
from app.models.equipment import Equipment, EquipmentType
from app.models.housing import Housing, Occupant, Occupancy, OccupancyStatusHistory, HousingStatusHistory, Unavailability, Cleaning, CleaningInvitationLog, EmailTemplate, EmailTemplateAttachment, EmailLog
from app.models.module import Module, ModuleConfig, ModuleStatus
from app.models.maintenance import (
    AIConversation,
    AIMessage,
    ContractEquipment,
    MaintenanceContract,
    MaintenanceCost,
    MaintenanceIntervenant,
    MaintenanceIntervention,
    MaintenancePart,
    MaintenancePlan,
    MaintenancePlanChecklist,
    MaintenanceProvider,
    MaintenanceRequest,
    MaintenanceStatusHistory,
    MaintenanceWorkOrder,
    WorkOrderPart,
)
from app.models.rbac import (
    Group,
    GroupRole,
    Permission,
    PermissionModel,
    Role,
    RolePermission,
    UserGroup,
    UserRoleAssignment,
)
from app.models.user import User, UserRole
from app.models.volunteer import Volunteer
from app.models.sport import SportActivity, SportAthlete, SportGarminConnection, SportGarminSyncLog, SportGoal, SportTrackPoint
from app.models.administrative import AdministrativeAssignment, AdministrativeCapability, AdministrativeMonthlySession, AdministrativeProgramType, AdministrativeRoleType, VolunteerCapability, VolunteerUnavailability

__all__ = [
    "ADConfig",
    "ADGroupMapping",
    "ADSyncLog",
    "ADSyncStatus",
    "AIConversation",
    "AIMessage",
    "AuditLog",
    "Base",
    "Building",
    "ContractEquipment",
    "Equipment",
    "EquipmentType",
    "Group",
    "GroupRole",
    "Housing",
    "HousingStatusHistory",
    "MaintenanceContract",
    "MaintenanceCost",
    "MaintenanceIntervenant",
    "MaintenanceIntervention",
    "MaintenancePart",
    "MaintenancePlan",
    "MaintenancePlanChecklist",
    "MaintenanceProvider",
    "MaintenanceRequest",
    "MaintenanceStatusHistory",
    "MaintenanceWorkOrder",
    "Module",
    "ModuleConfig",
    "ModuleStatus",
    "Occupancy",
    "OccupancyStatusHistory",
    "Occupant",
    "Cleaning",
    "CleaningInvitationLog",
    "EmailTemplate",
    "EmailTemplateAttachment",
    "EmailLog",
    "Permission",
    "PermissionModel",
    "Role",
    "RolePermission",
    "Room",
    "RoomType",
    "Site",
    "Unavailability",
    "User",
    "UserGroup",
    "UserRole",
    "UserRoleAssignment",
    "Volunteer",
    "UsageType",
    "SportActivity",
    "SportAthlete",
    "SportGoal",
    "SportTrackPoint",
    "SportGarminConnection",
    "SportGarminSyncLog",
    "WorkOrderPart",
    "AdministrativeAssignment",
    "AdministrativeCapability",
    "AdministrativeMonthlySession",
    "AdministrativeProgramType",
    "AdministrativeRoleType",
    "VolunteerCapability",
    "VolunteerUnavailability",
]
